version: '2'

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/usr/src/app
    env_file: .env
    depends_on:
      - postgres
      - redis
    command: coverage run manage.py test political_advisor

  postgres:
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
