version: '2'

services:
  sut:
    extends:
      file: docker-compose-common.yml
      service: sut
    depends_on:
      - postgres
      - redis
    command: coverage run manage.py test political_advisor

  postgres:
    extends:
      file: docker-compose-common.yml
      service: postgres
    ports:
      - "5432:5432"

  redis:
    extends:
      file: docker-compose-common.yml
      service: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
  redisdata:
