version: '2'

services:
  web:
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file: .env
    environment:
      DEBUG: 'true'
      PYTHONUNBUFFERED: 0
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
