sut:
  build: ./web
  dockerfile: Dockerfile.test
  env_file: .env
  volumes_from:
    - web
  links:
    - postgres:postgres
    - redis:redis
    - web:web
  command: /usr/local/bin/python manage.py test myapp

web:
  build: ./web
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - /usr/src/app
    - /usr/src/app/myapp/static
  env_file: .env
  environment:
    DEBUG: 'true'
  command: sh /usr/src/app/docker-web-script.sh

postgres:
  image: postgres:latest
  volumes:
    - pgdata:/var/lib/postgresql/data/

redis:
  image: redis:latest
  volumes:
    - redisdata:/data