sut:
  build: ./web
  dockerfile: Dockerfile.test
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./web:/usr/src/app
  env_file: .env
  command: /usr/local/bin/python manage.py test myapp

postgres:
  image: postgres:latest
  volumes:
    - pgdata:/var/lib/postgresql/data/

redis:
  image: redis:latest
  volumes:
    - redisdata:/data
