version: '2'
services:
  sut:
    build:
      context: ./web
      dockerfile: Dockerfile.test
    depends_on:
      - postgres
      - redis
    volumes:
      - ./web:/usr/src/app
    env_file: .env
#    command: coverage run --source django_political_advisor run_tests.py
#    command: /usr/local/bin/python manage.py test django_political_advisor
    command: coverage run manage.py test django_political_advisor

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata: