version: '2'

services:
  web:
    restart: always
    expose:
      - "8000"
    volumes:
      - .:/usr/src/app/
    env_file: .env
    command: sh /usr/src/app/docker-web-script.sh

  nginx:
    build:
      context: ./nginx/
    restart: always
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    depends_on:
      - web

  postgres:
    restart: always
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    ports:
      - "6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: