version: '2'

services:
  web:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    env_file: .env

  sut:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/usr/src/app
    env_file: .env

  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    volumes:
      - redisdata:/data
