web:
  build: ./web
  dockerfile: Dockerfile.dev
  ports:
    - "8000:8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./web:/usr/src/app
  env_file: .env
  environment:
    DEBUG: 'true'
    PYTHONUNBUFFERED: 0
  command: /usr/local/bin/python manage.py runserver 0.0.0.0:8000

postgres:
  image: postgres:latest
  volumes:
    - pgdata:/var/lib/postgresql/data/

redis:
  image: redis:latest
  volumes:
    - redisdata:/data
