version: '2'

services:
  web:
    extends:
      file: docker-compose-common.yml
      service: web
    restart: always
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis
    command: sh /usr/src/app/docker-web-script.sh

  nginx:
    build:
      context: ./nginx/
    restart: always
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    depends_on:
      - web

  postgres:
    file: docker-compose-common.yml
      service: postgres
    restart: always
    ports:
      - "5432"

  redis:
    file: docker-compose-common.yml
      service: redis
    restart: always
    ports:
      - "6379"

volumes:
  pgdata:
  redisdata:
